/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    GridBox: typeof import('./src/components/GridBox.vue')['default']
    GridContent: typeof import('./src/components/GridContent.vue')['default']
    ModuleTitle: typeof import('./src/components/ModuleTitle.vue')['default']
    QuickSwitchingText: typeof import('./src/components/QuickSwitchingText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
  }
}
